# Global Values
repoUrl: 'https://github.com/mad-underground/eks-services-non-production'
targetRevision: HEAD
region: ''
account: ''
clusterName: ''

# Kubernetes Dashboard Values
kubernetesDashboard:
  enable: true
  serviceAccountName:

# Metrics Server Values
metricsServer:
  enable: true


# Argo Work Flows Values
argoWorkflows:
  enable: true