# Global Values
repoUrl: https://gitlab.com/mad-underground/gitops/kubernetes/eks-services-non-production.git
targetRevision: main
region: ''
account: ''
clusterName: ''

# Kubernetes Dashboard Values
kubernetesDashboard:
  enable: true
  serviceAccountName:

# Metrics Server Values
metricsServer:
  enable: true

# Argo Work Flows Values
argoWorkflows:
  enable: true
